### ISSUE TITLE
Is it Possible to Preserve the Parent Page With This Library?

### ISSUE THREAD

**Issue by machineghost** [toomuchdesign/next-use-contextual-routing#7]
## 💬 Questions and Help

If you look at https://toomuchdesign.github.io/next-use-contextual-routing/ you'll see that when you open (say) post #1, and then refresh the page, you lose the page "behind" post #1 (ie. the initial page).

I'm looking for a _very_ similar effect, except I want to preserve the "behind page" on refreshes, so that the user sees the same page that they saw before they refreshed, afterward.  It is it possible to use the library in this way, eg. by somehow providing the "before page" (or path) to `useContextualRouting()`?

**Comment by toomuchdesign** [comment]
If the page renders the same during both client navigation and ssr render, you seem not to need contextual navigation. Just render the "behind page" in your child routes.

Otherwise Next.js couldn't tell a normal post page from a post + behind page at ssr time since they would both have the same url.
